config/routes.rb
Qa::Application.routes.draw do

  root to: 'static_pages#home'
  resources :users, only: [:new, :create]
  resource :sessions, only: [:destroy]

  match '/about',   to: 'static_pages#about'
  match '/home', to: 'users#home'

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :netid, presence: true, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def destroy
		sign_out
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		redirect_to home_path
  	end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter
  before_filter :signed_in_user, only: [:home]
  before_filter :not_signed_in, only: [:new]

  def new
  	@netid = session[:cas_user]
    ldap_con = initialize_ldap_con()

  	@user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Great! You're ready to get started!"
      redirect_to home_path
    else
      @netid = session[:cas_user]
      flash[:error] = "Sorry, that information is invalid. Please make sure to include a first and last name."
      render :new
    end
  end

  def home
  end

  private
  	def signed_in_user
      unless signed_in?
        redirect_to new_user_path, notice: "Please create an account."
      end
    end

    def not_signed_in
      if signed_in?
        flash[:error] = "You already have an account!"
        redirect_to home_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_out
		current_user = nil
		session.delete(:cas_user)
		flash[:notice] = "</pre>You have signed out. To sign out of Yale CAS, <a href=\"https://secure.its.yale.edu/cas/logout\"> click here.</a>"
		redirect_to root_path
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user
		@current_user ||= user_from_netid
	end

	def current_user?(user)
		user == current_user
	end

	def user_from_netid
		netid = session[:cas_user]
		@current_user = User.find_by_netid(netid) unless netid.nil?
	end

	protected
		
		def current_user=(user)
			@current_user = user
		end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "dear prof", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "About",    about_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Sign in", home_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
   	  <% flash.each do |key, value| %>
         <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
<h1>Welcome to Dear Prof</h1>
<p>You can use this website to ask questions anonymously to your professors.</p>
<%= link_to "Get started now!", home_path, class: 'btn btn-large btn-primary'  %>
</div>

app/views/users/home.html.erb
<% provide(:title, "Dear Prof | #{current_user.first_name}") %>
<div class="center hero-unit" >
<h1>Welcome, <%= current_user.first_name + " " + current_user.last_name %></h1>
<p>To get started, you'll need to <%= link_to "add some classes", '#', class: 'badge' %>.</p>

</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
	<%= f.label :netid, "Net ID" %>
	<%= f.text_field :netid, value: @netid, readonly: true %>

	<%= f.label :first_name %>
	<%= f.text_field :first_name %>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %>

	<br />

	<%= f.submit "Create account", class: 'btn-primary btn' %>
<% end %>